function Expand-ZIPFile($file, $destination)
{
    $shell = new-object -com shell.application
    $zip = $shell.NameSpace($file)
    foreach($item in $zip.items())
    {
        $shell.Namespace($destination).copyhere($item)
    }
}

$path = $env:LocalAppData + "\Niklas_Mollenhauer\"
$config = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjxjb25maWd1cmF0aW9uPg0KICAgIDxjb25maWdTZWN0aW9ucz4NCiAgICAgICAgPHNlY3Rpb25Hcm91cCBuYW1lPSJ1c2VyU2V0dGluZ3MiPg0KICAgICAgICAgICAgPHNlY3Rpb24gbmFtZT0iQ3VzdG9tUG9zdFVwbG9hZC5Qcm9wZXJ0aWVzLlNldHRpbmdzIiB0eXBlPSJTeXN0ZW0uQ29uZmlndXJhdGlvbi5DbGllbnRTZXR0aW5nc1NlY3Rpb24sIFN5c3RlbSwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkiIGFsbG93RXhlRGVmaW5pdGlvbj0iTWFjaGluZVRvTG9jYWxVc2VyIiByZXF1aXJlUGVybWlzc2lvbj0iZmFsc2UiIC8+DQogICAgICAgIDwvc2VjdGlvbkdyb3VwPg0KICAgIDwvY29uZmlnU2VjdGlvbnM+DQogICAgPHVzZXJTZXR0aW5ncz4NCiAgICAgICAgPEN1c3RvbVBvc3RVcGxvYWQuUHJvcGVydGllcy5TZXR0aW5ncz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9InBvc3RDb25maWciIHNlcmlhbGl6ZUFzPSJYbWwiPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT4NCiAgICAgICAgICAgICAgICAgICAgPFBvc3RDb25maWcgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSI+DQogICAgICAgICAgICAgICAgICAgICAgICA8UG9zdERhdGE+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHN0cmluZz5hcGlrZXk9SU5TRVJUQVBJS0VZSEVSRTwvc3RyaW5nPg0KICAgICAgICAgICAgICAgICAgICAgICAgPC9Qb3N0RGF0YT4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxQb3N0SW1hZ2VEYXRhRmllbGQ+aW1hZ2U8L1Bvc3RJbWFnZURhdGFGaWVsZD4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxQb3N0VGFyZ2V0VXJsPmh0dHBzOi8vc2NyZWVuc2hvdC5uaWdodHdpcmUuZGUvaGFuZGxlLnBocDwvUG9zdFRhcmdldFVybD4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxSZXN1bHRSZWdleFBhdHRlcm4+I3N1Y2Nlc3MgKD8mbHQ7bGluayZndDsuKik8L1Jlc3VsdFJlZ2V4UGF0dGVybj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxGYWlsUmVnZXhQYXR0ZXJuPiNlcnJvciAoPyZsdDtlcnJvciZndDsuKik8L0ZhaWxSZWdleFBhdHRlcm4+DQogICAgICAgICAgICAgICAgICAgICAgICA8VXNlckFnZW50Pk5pZ2h0d2lyZS1Ib2x6c2hvdHM8L1VzZXJBZ2VudD4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxNYXhGaWxlU2l6ZT45NDM4MjMyNTc2PC9NYXhGaWxlU2l6ZT4NCiAgICAgICAgICAgICAgICAgICAgPC9Qb3N0Q29uZmlnPg0KICAgICAgICAgICAgICAgIDwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJVcGdyYWRlZCIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPlRydWU8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICA8L0N1c3RvbVBvc3RVcGxvYWQuUHJvcGVydGllcy5TZXR0aW5ncz4NCiAgICAgICAgPEhvbHpTaG90cy5NeS5NeVNldHRpbmdzPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0iRW5hYmxlSW5nYW1lTW9kZSIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPkZhbHNlPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9InN0YXJ0X3dpdGhfd2luZG93cyIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPlRydWU8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0iZW5hYmxlU3RhdHVzVG9hc3RlciIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPlRydWU8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0iZW5hYmxlV2luZG93U2NyZWVuc2hvdCIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPlRydWU8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0iZW5hYmxlRnVsbHNjcmVlblNjcmVlbnNob3QiIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5UcnVlPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9ImVuYWJsZUFyZWFTY3JlZW5zaG90IiBzZXJpYWxpemVBcz0iU3RyaW5nIj4NCiAgICAgICAgICAgICAgICA8dmFsdWU+VHJ1ZTwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJEb2NrTG9jYXRpb24iIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5EaXNhYmxlZDwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJBdXRvQ2xvc2VMaW5rVmlld2VyIiBzZXJpYWxpemVBcz0iU3RyaW5nIj4NCiAgICAgICAgICAgICAgICA8dmFsdWU+VHJ1ZTwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJBdXRvQ2xvc2VUaHVtYlZpZXdlciIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPlRydWU8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0iVXBncmFkZWQiIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5UcnVlPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9IlN0YW5kYXJkSW1hZ2VIb3N0ZXIiIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5DdXN0b20tUG9zdDwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJlbmFibGVMaW5rVmlld2VyIiBzZXJpYWxpemVBcz0iU3RyaW5nIj4NCiAgICAgICAgICAgICAgICA8dmFsdWU+RmFsc2U8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0idXNlclRhc2tzSW5pdGlhbGl6ZWQiIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5UcnVlPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9ImVuYWJsZVNob3RFZGl0b3IiIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5GYWxzZTwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJTY3JlZW5zaG90UGF0aCIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPkQ6XDAxX0Nsb3VkXFNvZm9ydFVwbG9hZDwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJzYXZlSW1hZ2VzVG9Mb2NhbERpc2siIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5UcnVlPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9IlNhdmVJbWFnZXNQYXR0ZXJuIiBzZXJpYWxpemVBcz0iU3RyaW5nIj4NCiAgICAgICAgICAgICAgICA8dmFsdWU+Jmx0O0ZpbGU6U2VxdWVuY2VOdW1iZXImZ3Q7PC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9IkZpbGVTZXF1ZW5jZU51bWJlciIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPjUxODwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJUcmF5SWNvbkRvdWJsZUNsaWNrQWN0aW9uIiBzZXJpYWxpemVBcz0iU3RyaW5nIj4NCiAgICAgICAgICAgICAgICA8dmFsdWU+T3BlblNldHRpbmdzPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9IlNlbGVjdGlvbkRlY29yYXRpb24iIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5Ob21pbmF0aW9uMTwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJFbmFibGVTbWFydEZvcm1hdEZvclVwbG9hZCIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPlRydWU8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0iRW5hYmxlU21hcnRGb3JtYXRGb3JTYXZpbmciIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5UcnVlPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9IkVuYWJsZURlYnVnTW9kZSIgc2VyaWFsaXplQXM9IlN0cmluZyI+DQogICAgICAgICAgICAgICAgPHZhbHVlPkZhbHNlPC92YWx1ZT4NCiAgICAgICAgICAgIDwvc2V0dGluZz4NCiAgICAgICAgICAgIDxzZXR0aW5nIG5hbWU9ImlzRmlyc3RSdW4iIHNlcmlhbGl6ZUFzPSJTdHJpbmciPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT5GYWxzZTwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJ3aW5kb3dIb3RrZXkiIHNlcmlhbGl6ZUFzPSJYbWwiPg0KICAgICAgICAgICAgICAgIDx2YWx1ZT4NCiAgICAgICAgICAgICAgICAgICAgPEtleVN0cm9rZSB4bWxuczp4c2Q9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxLZXk+RjI8L0tleT4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxNb2RrZXk+Q29udHJvbDwvTW9ka2V5Pg0KICAgICAgICAgICAgICAgICAgICA8L0tleVN0cm9rZT4NCiAgICAgICAgICAgICAgICA8L3ZhbHVlPg0KICAgICAgICAgICAgPC9zZXR0aW5nPg0KICAgICAgICAgICAgPHNldHRpbmcgbmFtZT0iZnVsbEhvdGtleSIgc2VyaWFsaXplQXM9IlhtbCI+DQogICAgICAgICAgICAgICAgPHZhbHVlPg0KICAgICAgICAgICAgICAgICAgICA8S2V5U3Ryb2tlIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiPg0KICAgICAgICAgICAgICAgICAgICAgICAgPEtleT5GMzwvS2V5Pg0KICAgICAgICAgICAgICAgICAgICAgICAgPE1vZGtleT5Db250cm9sPC9Nb2RrZXk+DQogICAgICAgICAgICAgICAgICAgIDwvS2V5U3Ryb2tlPg0KICAgICAgICAgICAgICAgIDwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgICAgICA8c2V0dGluZyBuYW1lPSJzZWxlY3RvckhvdGtleSIgc2VyaWFsaXplQXM9IlhtbCI+DQogICAgICAgICAgICAgICAgPHZhbHVlPg0KICAgICAgICAgICAgICAgICAgICA8S2V5U3Ryb2tlIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiPg0KICAgICAgICAgICAgICAgICAgICAgICAgPEtleT5GNDwvS2V5Pg0KICAgICAgICAgICAgICAgICAgICAgICAgPE1vZGtleT5Db250cm9sPC9Nb2RrZXk+DQogICAgICAgICAgICAgICAgICAgIDwvS2V5U3Ryb2tlPg0KICAgICAgICAgICAgICAgIDwvdmFsdWU+DQogICAgICAgICAgICA8L3NldHRpbmc+DQogICAgICAgIDwvSG9selNob3RzLk15Lk15U2V0dGluZ3M+DQogICAgPC91c2VyU2V0dGluZ3M+DQo8L2NvbmZpZ3VyYXRpb24+"
$apikey = Read-Host("Bitte API Key eingeben")
$pluginPath = $env:AppData + "\HolzShots\Plugin\"

#Prepare Directorys
Write-Host("Erstelle HolzShots Programm Ordner")
Remove-Item ($env:LocalAppData + "\HolzShots") -recurse
$HZPath = (New-Item -ItemType Directory -Force -Path ($env:LocalAppData + "\HolzShots")).FullName

Write-Host("Erstelle HolzShots Plugin Ordner")
Remove-Item $pluginPath -recurse
New-Item -ItemType Directory -Force -Path $pluginPath

Write-Host("Erstelle HolzShots Settings Ordner")
Remove-Item $path -recurse
New-Item -ItemType Directory -Force -Path $path

#Download Holzshots
Write-Host("Lade HolzShots runter..")
$url = "https://gitlab.com/nightwire/NWDE-Holzshots/raw/49e3085b851b63c5c9cf3b5d85c692ffda79157d/HolzShots.zip"
$output = "$HZPath\HolzShots.zip"

Invoke-WebRequest -Uri $url -OutFile $output

#Unzip Holzshots
Write-Host("Entpacke HolzShots..")
Expand-ZIPFile -File $output -Destination $HZPath

#Delete Zip
Write-Host("Lösche HolzShots Archiv..")
Remove-Item -Force $output

#Add Holzshots to autostart
#$UserConfigDestination = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup" 
#AddItemToStartup -ItemName ($HZPath + "\HolzShots.exe") -Destination $UserConfigDestination 

#Copy CustomPost Plugin
Write-Host("Kopiere Custom Post Plugin..")
Copy-Item -Force ($HZPath + "\CustomPostUpload.dll") -Destination ($pluginPath + "\CustomPostUpload.dll")

#Start Holzshots once, wait a few seconds and kill it right away
Write-Host("Starte HolzShots, um entsprechenden Config Pfad zu erkennen.")

$Process = [Diagnostics.Process]::Start(($HZPath + "\Holzshots.exe"))
$id = $Process.Id

Write-Host("Warte 10 Sekunden..")
Start-Sleep -Seconds 10

try {            
    Stop-Process -Id $id -ErrorAction stop            
    Write-Host "Erfolgreich Holzshots mit der ID: $id gestoppt."            
} catch {            
    Write-Host "FEHLER: Bitte Holzshots manuell neustarten."            
}

#Add Config
Get-ChildItem $path | ForEach-Object{

    Remove-Item $_.FullName -recurse     
    $ConfigFolder = New-Item -ItemType directory -Path ($_.FullName + "\" + "0.9.8.12")
        
    $configPath = $ConfigFolder.FullName + "\user.config"

    $configContent = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($config))
    $configContent = $configContent.Replace('INSERTAPIKEYHERE', $apikey)
    $configContent | Set-Content -Encoding UTF8 $configPath
    Write-Host("HolzShots Config erfolgreich unter $configPath gespeichert")
    
}

Write-Host("Installation erfolgreich, starte Holzshots.")
[Diagnostics.Process]::Start(($HZPath + "\Holzshots.exe"))